backup_prompt="Backup Unused?"

backup_continue="Press Y to continue or any key to return to the menu"

backups_off="\nBackups Disabled! Unused files will be left where they are\n\n"

backups_on="\nBackups enabled!\n\n"

continue="Press any key to continue..."

empty_choice="\nNo choice entered"

env_missing="location not set in"

invalid_choice="Invalid option:"

no_igir="
                                          *** IGIR not found! ***

    *** Place the IGIR Binary in with this script or set it's location in igirst.cfg ***

"

quit="\nExiting IGIR Shell Tools..."
