#Common menu variables
choose="Choose a Platform"
menu_row_1="            ****************************************************"
menu_row_2="            *                                                  *"
menu_row_3="            *                IGIR SHELL TOOLS                  *"
menu_row_4="            *                                                  *"
menu_row_6="            *                                                  *"
menu_row_7="            ****************************************************"

command_menu_list="Choose a command (0-8):

1: Generate Report Only
2: Scan and Copy Roms
3: Scan and Move Roms
4: Scan and Copy Roms(Backup Unused)
5: Scan and Move Roms(Backup Unused)
6: Scan and Copy Roms(Recycle Unused)
7: Scan and Move Roms(Recycle Unused)
8: Previous Menu
9: Main Menu
0: Quit

"

main_menu_header="
$menu_row_1
$menu_row_2
$menu_row_3
$menu_row_4
            *                    Main Menu                     *
$menu_row_6
$menu_row_7

"

main_menu_list="$choose or Manufacturer(0-5):

1: Atari
2: NEC
3: Nintendo
4: Sega
5: SNK
0: Quit

"

atari_menu_header="
$menu_row_1
$menu_row_2
$menu_row_3
$menu_row_4
            *                     Atari                        *
$menu_row_6
$menu_row_7

"

atari_menu_list="$choose(0-6):

1: 2600
2: 5200
3: 7800
4: Jaguar
5: Lynx
6: Main Menu
0: Quit

"

nec_menu_header="
$menu_row_1
$menu_row_2
$menu_row_3
$menu_row_4
            *                      NEC                         *
$menu_row_6
$menu_row_7

"

nec_menu_list="$choose(0-2):

1: TurboGrafx 16\PC Engine
2: Main Menu
0: Quit

"

nintendo_menu_header="
$menu_row_1
$menu_row_2
$menu_row_3
$menu_row_4
            *                    Nintendo                      *
$menu_row_6
$menu_row_7

"

nintendo_menu_list="$choose(0-10):

1: 3DS
2: 64
3: DS
4: Game Boy
5: Game Boy Advance
6: Game Boy Color
7: Nintendo Entertainment System
8: Super Nintendo Entertainment System
9: Virtual Boy
10: Main Menu
0: Quit

"

nintendo_3ds_menu_header="
$menu_row_1
$menu_row_2
$menu_row_3
$menu_row_4
            *                 Nintendo - 3DS                   *
$menu_row_6
$menu_row_7
            
"

nintendo_64_menu_header="
$menu_row_1
$menu_row_2
$menu_row_3
$menu_row_4
            *                 Nintendo - 64                    *
$menu_row_6
$menu_row_7
            
"

nintendo_ds_menu_header="
$menu_row_1
$menu_row_2
$menu_row_3
$menu_row_4
            *                 Nintendo - DS                    *
$menu_row_6
$menu_row_7
            
"

nintendo_gb_menu_header="
$menu_row_1
$menu_row_2
$menu_row_3
$menu_row_4
            *               Nintendo - Game Boy                *
$menu_row_6
$menu_row_7
            
"

nintendo_gbc_menu_header="
$menu_row_1
$menu_row_2
$menu_row_3
$menu_row_4
            *            Nintendo - Game Boy Color             *
$menu_row_6
$menu_row_7
            
"

nintendo_gba_menu_header="
$menu_row_1
$menu_row_2
$menu_row_3
$menu_row_4
            *          Nintendo - Game Boy Advance             *
$menu_row_6
$menu_row_7
            
"

nintendo_nes_menu_header="
$menu_row_1
$menu_row_2
$menu_row_3
$menu_row_4
            *     Nintendo - Nintendo Entertainment System     *
$menu_row_6
$menu_row_7
            
"

nintendo_snes_menu_header="
$menu_row_1
$menu_row_2
$menu_row_3
$menu_row_4
            *  Nintendo - Super Nintendo Entertainment System  *
$menu_row_6
$menu_row_7
            
"

nintendo_vb_menu_header="
$menu_row_1
$menu_row_2
$menu_row_3
$menu_row_4
            *             Nintendo - Virtual Boy               *
$menu_row_6
$menu_row_7
            
"

sega_menu_header="
$menu_row_1
$menu_row_2
$menu_row_3
$menu_row_4
            *                      Sega                        *
$menu_row_6
$menu_row_7

"

sega_menu_list="$choose(0-5):

1: 32X
2: Game Gear
3: Genesis\Mega Drive
4: Master System
5: Main Menu
0: Quit

"

snk_menu_header="
$menu_row_1
$menu_row_2
$menu_row_3
$menu_row_4
            *                      SNK                         *
$menu_row_6
$menu_row_7

"

snk_menu_list="$choose(0-2):

1: Neo Geo Pocket Color
2: Main Menu
0: Quit

"
