#!/bin/bash

backup_prompt=" *** WARNING! *** Clean is enabled but backups are not. Are you sure you want to continue?
"

backup_continue="
 Press Y to continue or any other key to return to the previous menu
"

continue="
 Press any key to continue...
"

empty_choice="
 No choice entered"

var_missing="location not set in igirst.cfg"

invalid_choice="
 Invalid option:"

no_igir="
                                          *** IGIR not found! ***

    *** Place the IGIR Binary in with this script or set it's location in igirst.cfg ***

"

quit="
 Exiting IGIR Shell Tools...
"
