#!/bin/bash

backup_prompt="Backup Unused?"

backup_continue="
Press Y to continue or any key to return to the previous menu
"

backups_off="
Backups Disabled! Unused files will be left where they are
"

backups_on="
Backups enabled!
"

continue="
Press any key to continue...
"

empty_choice="
No choice entered"

var_missing="location not set in"

invalid_choice="
Invalid option:"

no_igir="
                                          *** IGIR not found! ***

    *** Place the IGIR Binary in with this script or set it's location in igirst.cfg ***

"

quit="
Exiting IGIR Shell Tools...
"
